name: update

on:
  repository_dispatch:
    types:
      - tibiadata-api-docs-release-update

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd #v5.0.1

      - name: Download swagger.json from tibiadata-api-go release
        uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05 #v1.12
        with:
          repository: tibiadata/tibiadata-api-go
          tag: ${{ github.event.client_payload.tag_name }}
          fileName: swagger.json
          out-file-path: docs

      - name: Manipulate docs/swagger files with custom settings
        run: |
          # set scheme for server to only https
          contents="$(jq '.schemes = ["https"]' docs/swagger.json)" && \
          echo "${contents}" > docs/swagger.json

          # making copy for new synced dev doc
          cp docs/swagger.json docs/swagger-dev.json

          # set api hosts
          contents_api="$(jq '.host = "api.tibiadata.com"' docs/swagger.json)" && \
          contents_dev="$(jq '.host = "dev.tibiadata.com"' docs/swagger-dev.json)" && \
          echo "${contents_api}" > docs/swagger.json
          echo "${contents_dev}" > docs/swagger-dev.json

          # set version for dev to edge
          contents="$(jq '.info.version = "edge"' docs/swagger-dev.json)" && \
          echo "${contents}" > docs/swagger-dev.json

      - name: Commit docs/swagger files to repo
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 #v9.1.4
        with:
          add: docs/swagger.json docs/swagger-dev.json
          message: automatic update of docs/swagger files (release ${{ github.event.client_payload.tag_name }})

  deploy:
    runs-on: ubuntu-latest
    needs: update
    steps:
      - name: Trigger github-pages workflow
        uses: peter-evans/repository-dispatch@5fc4efd1a4797ddb68ffd0714a238564e4cc0e6f #v4.0.0
        with:
          event-type: tibiadata-api-docs-deploy
