name: update

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download latest swagger.json from tibiadata-api-go
        uses: i3h/download-release-asset@v1.3.2
        with:
          owner: TibiaData
          repo: tibiadata-api-go
          tag: latest
          file: swagger.json
          path: docs
          token: ${{ github.GITHUB_TOKEN }}

      - name: Manipulate swagger.json with custom settings
        id: swagger-manipulation
        run: |
          # set api host to api.tibiadata.com
          contents="$(jq '.host = "dev.tibiadata.com"' docs/swagger.json)" && \
          echo "${contents}" > docs/swagger.json

          # set scheme for server to only https
          contents="$(jq '.schemes = ["https"]' docs/swagger.json)" && \
          echo "${contents}" > docs/swagger.json

          # getting release version from swagger file
          echo "::set-output name=release::$(cat docs/swagger.json | jq -r .info.version)"

      - name: Commit swagger.json to repo
        uses: EndBug/add-and-commit@v7
        with:
          add: docs/swagger.json
          message: automatic update of swagger.json (release ${{ steps.swagger-manipulation.outputs.release }})
